spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope: profile, email
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    bearer-type: Bearer
    access-token-expiration:  2592000000 # 30일 (한 달)  #3600000 : 1시간
    refresh-token-expiration: 1209600000

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

    elasticsearch:
      host: ${ELASTICSEARCH_HOST}
      port: ${ELASTICSEARCH_PORT}
      encodedApiKey: ${ELASTICSEARCH_ENCODED_API_KEY}
      user-name : ${ELASTICSEARCH_USER_NAME}
      password : ${ELASTICSEARCH_PASSWORD}
      repositories:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
      type: trace
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

cloud:
  gcp:
    storage:
      bucket: knulinkmoa-bucket

